<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-KAC3CU8" name="com.cm.qa.testcases.PasswordPageTests" tests="6" failures="0" timestamp="26 Jan 2020 17:33:10 GMT" time="0.001" errors="1">
  <testcase name="setUp" time="0.001" classname="com.cm.qa.testcases.PasswordPageTests">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at cm.cm.qa.base.TestBase.initializeBrowser(TestBase.java:70)
at com.cm.qa.testcases.PasswordPageTests.setUp(PasswordPageTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="verifyUsernameLabelTest" time="0.000" classname="com.cm.qa.testcases.PasswordPageTests">
    <skipped/>
  </testcase> <!-- verifyUsernameLabelTest -->
  <testcase name="blankPasswordTest" time="0.000" classname="com.cm.qa.testcases.PasswordPageTests">
    <skipped/>
  </testcase> <!-- blankPasswordTest -->
  <testcase name="invalidPasswordTest" time="0.000" classname="com.cm.qa.testcases.PasswordPageTests">
    <skipped/>
  </testcase> <!-- invalidPasswordTest -->
  <testcase name="verifyPasswordScreenFooterTextTest" time="0.000" classname="com.cm.qa.testcases.PasswordPageTests">
    <skipped/>
  </testcase> <!-- verifyPasswordScreenFooterTextTest -->
  <testcase name="validPasswordTest" time="0.000" classname="com.cm.qa.testcases.PasswordPageTests">
    <skipped/>
  </testcase> <!-- validPasswordTest -->
</testsuite> <!-- com.cm.qa.testcases.PasswordPageTests -->
